### ISSUE TITLE
inference does not work in case of curried function and `_`

### ISSUE THREAD

**Issue by robstoll** [lampepfl/dotty-feature-requests#111]
Consider the following:
```
trait A[T]
object Main {
  def foo[T](f: (=> Int => A[T]) => A[T]) = ???
  def bar[T](): Int = ???
  def main(args: Array[String]): Unit = {
    foo[String](_(bar())) // works as expected
    val m: Seq[(String, (=> Int => A[String]) => A[String])] = Seq(
      "a" -> (_(bar()))   // works as expected
      //"b" -> _(bar())   // hoped this works in dotty as well, uncomment and the compiler fails with:
                          // Missing parameter type
                          // I could not infer the type of the parameter _$3.
    )
  } 
}
```

Would be nice if it worked without the additional parenthesis but really just a nice-to-have

**Comment by smarter** [comment]
>       "a" -> (_(bar()))   // works as expected
>       //"b" -> _(bar())   // hoped this works in dotty as well, uncomment and the compiler fails with:

These expressions are not equivalent, parentheses are used when determining the scope of `_` in an expression. The first line desugars to:
```scala
"a" -> (x => x(bar())) 
```
whereas the second desugars to:
```scala
x => "b" -> x(bar())
```

**Comment by robstoll** [comment]
makes sense
```
("b", _(bar()))
```
works as I would expect
