### ISSUE TITLE
Support Vim-Style Command Abbreviations in the Repl

### ISSUE THREAD

**Issue by iamrecursion** [lampepfl/dotty-feature-requests#115]
The scala 2 repl supports vim-style command abbreviations with the standard disambiguation rules (e.g. the user can type `:q` for `:quit`, as long as `:q` isn't ambiguous. 

Given that Scala 2 has support for this abbreviated syntax, and that emulation of a vi(m)-style interface would lead users to expect it, I think that it would be good to add this to the dotty repl as well. 

@smarter has mentioned on [gitter](https://gitter.im/lampepfl/dotty?at=5eaec9fe7a24ff01b0fbca58) that it may be possible to borrow code from the scala 2 codebase to handle this.

**Comment by cb372** [comment]
Huh, I didn't know about this issue. I independently ran into the same problem and submitted the PR 😄

**Comment by iamrecursion** [comment]
I figured as much! I was planning on getting to it this weekend, but I'm not going to complain about you getting there first! 

Closed by [dotty#8901](https://github.com/lampepfl/dotty/pull/8901).

**Comment by som-snytt** [comment]
This one gets me every time!

I didn't know about the PR but just learned about this issue tracker and was curious what got fixed.

**Comment by iamrecursion** [comment]
The dotty repl now supports abbreviations!
