### ISSUE TITLE
Support -Yimports for implicit preamble imports

### ISSUE THREAD

**Issue by agilesteel** [lampepfl/dotty-feature-requests#138]
Is dotty going to support [this](https://github.com/scala/scala/pull/6764)? As of right now I'm getting `bad option -Yimports` and that's on `0.27.0-RC1`.

**Comment by som-snytt** [comment]
The implemented feature in scala 2 is "custom root contexts", as a more flexible variant of `-Yno-imports -Yno-predef`.

Maybe it will be more popular in combination with export clauses, which might simplify making a "custom predef".

Maybe the people will only accept constructing a namespace with no code but only config, `-Ynames:java.lang.String,cats._`.

Currently `object MyPredef { export java.lang.String }` doesn't do the obvious thing.

**Comment by benhutchison** [comment]
In my view, important capabilities that are not offered by the older `-Yimports` flag:

- Importing most of the existing Predef, but renaming or hiding a few members
- Importing specific classes or members from outside the std prelude packages
-  Control over whether `given`s are imported

**Comment by MateuszKubuszok** [comment]
At least some of Scala 2's limitations could be worked around in 3 with something like:

```scala
package com.company

// selecting what should be imported
object Predef:
  export scala.Predef.{any2stringadd as _, *}
  export cats.*
  // other exports exposing implicits, givens,
  // custom extension methods, etc
```

```
-Yimports:java.lang,scala,com.company.Predef // exports everything from custom Predef
```

This would allow filtering out implicits, givens and extension methods that we don't want to automatically export, let us rename things (`export x.{ y as z }`) and so one. The only potential issue would be scope cluttering, but if you could export everything that you are using more often that not, or if you want to encourage usage of some things, then it would be acceptable.
