### ISSUE TITLE
Better toString for case classes

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty-feature-requests#140]
Hello,

I made a plugin for Scala 2.x some time ago, which enhances the default implementation of case classes' toString. Could Dotty make this more of a native feature and provide a more detailed `toString` for case classes / enums by default?

Here's the plugin: https://github.com/kubukoz/better-tostring/

## Example

Current behavior in Scala 2.x with no plugins:

```scala
final case class User(name: String, age: Int)

User("Joe", 18).toString() // "User(Joe, 18)"
```

Improved:

```scala
User("Joe", 18).toString() // "User(name = Joe, age = 18)"
```

**Comment by smarter** [comment]
Discussed before at https://contributors.scala-lang.org/t/case-class-tostring-new-behavior-proposal-with-implementation/2056

**Comment by som-snytt** [comment]
Scala 2 has less whitespace:
```
scala> User("joe", 42)
val res0: User = User(joe,42)

scala> User("joe", 42).toString
val res1: String = User(joe,42)
```
This was deemed too much to change.

I tried to make [progress](https://github.com/scala/scala/pull/8885) just with printing in the REPL, to explore what is useful. (Quotes around strings, avoid `Some(value = "foo")`.) Probably the desired feature is just pretty printing.

**Comment by kubukoz** [comment]
Yeah, IME the highest impact usecase is recursive pretty printing in an interpolator. Ideally without compilation overhead, but I wouldn't personally mind extra milliseconds at runtime (or a compilation flag that optimizes for runtime). Just throwing ideas out there for 3.1+ ;)
