### ISSUE TITLE
throw when converting from a Java boxed type to a scala primitive

### ISSUE THREAD

**Issue by robstoll** [lampepfl/dotty-feature-requests#149]
Consider the following:
```
@main def main = {
  val jI: java.lang.Integer = null
  val i: Int                = jI  // 0
  val jB: java.lang.Boolean = null
  val b: Boolean            = jB // false
  println(s"Hi Scala 3! $i / $b")
}
```
I know, it's probably too late to make it into Scala 3 even though it would be the perfect time to introduce this breaking change. 
No idea why the implicit conversion behaves differently than when Java converts a boxed type to its primitive. 
I would have never expected such a Javascripty behaviour from scala :stuck_out_tongue: 

This is especially dangerous if you have something like:
```  
val jI: java.lang.Integer = null
Option[Int](jI) // Some(0)
```

**Comment by smarter** [comment]
We can't make that change without breaking the following (among other things):
```scala
class A[T] { var x: T = _ }
object B extends A[Int] { val y: Int = x }
println(B.y)
```
And in general we try to avoid changes that don't prevent code from compiling but make it do something different at runtime, those make it incredibly dangerous to upgrade code.

**Comment by robstoll** [comment]
I see, at least I know the reason now. Going to propose to IDE-devs to include a lint-check instead
