### ISSUE TITLE
Allow to omit structural part in given

### ISSUE THREAD

**Issue by rjolly** [lampepfl/dotty-feature-requests#156]
Here is a `given` example:
```scala
trait Ord[T]

abstract class Foo[T : Ord]:
 def foo: T

given [T : Ord] extends Foo[T] with
 def foo: T = ???
```
Imagine class `Foo` is concrete rather than abstract:
```scala
class ConcreteFoo[T : Ord]:
 def foo: T = ???

given [T : Ord]: ConcreteFoo[T] with {}
```
It should be possible to omit the structural part:
```scala
given [T : Ord]: ConcreteFoo[T]
```
Update : this is however the current syntax for abstract given. One possible way to avoid the collision is to disallow abstract given. However, it turns out to not be what we want. Another option would be to use `extends` instead of `:` in the given instance case:
```scala
given c: C // abstract
given c: C = new C // given alias
given C = new C // anonymous
given C // given instance; no confusion with abstract since abstract cannot be anonymous
given c extends C // named instance
```
Notice that we would have to first parse given alias, and then backtrack to given instance in case there's no equal sign:
```scala
given C = new C
given C
```

**Comment by som-snytt** [comment]
I think the edited comment concedes that this request can be closed. Or is there a forlorn hope for `extends` syntax? The forum post conceded that as well.

**Comment by rjolly** [comment]
Yes. I think we can now avoid the problematic `with {}` like so:
```scala
given [T : Ord]: ConcreteFoo[T]()
```
And in https://contributors.scala-lang.org/t/something-still-not-right-with-givens/4766 I concluded that there is a reasoning by which it could be justified anyway.
