### ISSUE TITLE
val not allowed in extension block

### ISSUE THREAD

**Issue by dhinojosa** [lampepfl/dotty-feature-requests#160]
## Minimized code

In Scala 2 I can do the following and works, notice just one `implictly`
```Scala
implicit class MyWrapper[A:Numeric](a:A) {
    val numeric = implicitly[Numeric[A]]
    def cubed:A = numeric.times(a, numeric.times(a,a))
    def beforeAndAfter(b:A):(A,A,A) =  (numeric.minus(a,b), a, numeric.plus(a,b))
}
```

In Scala 3, when I try to do the following it results in multiple compile-time errors

```Scala
 extension [A : Numeric](a:A)
    val numeric = summon[Numeric[A]]
    def cubed:A =   
      numeric.times(a, numeric.times(a, a))
    def beforeAndAfter(b:A):(A,A,A) = 
      (numeric.minus(a,b), a, numeric.plus(a,b))
```

## Output

```scala
val numeric = summon[Numeric[A]]
[error]    |    ^^^
[error]    |    'def' expected, but 'val' found

val numeric = summon[Numeric[A]]
[error]    |        ^^^^^^^
[error]    |        ';' expected, but identifier found

numeric.times(a, numeric.times(a, a))
[error]    |      ^^^^^^^
[error]    |      Not found: numeric

(numeric.minus(a,b), a, numeric.plus(a,b))
[error]    |       ^^^^^^^
[error]    |       Not found: numeric
```

## Expectation

Should work the same as Scala 2 using an `implicit class` and `implicitly`.  The workaround is performing duplication as follows

```Scala
  extension[A : Numeric](a:A)
    def cubed:A =   
      val numeric = summon[Numeric[A]]
      numeric.times(a, numeric.times(a, a))
    def beforeAndAfter(b:A):(A,A,A) = 
      val numeric = summon[Numeric[A]]
      (numeric.minus(a,b), a, numeric.plus(a,b))
```

**Comment by SethTisue** [comment]
Why does the `def` version even compile? I thought `extension` didn't open a scope, as per Martin's https://contributors.scala-lang.org/t/feedback-sought-optional-braces/4702/60 (“collective extension methods are not like classes or objects since they do not open a nested scope”) and https://dotty.epfl.ch/docs/reference/contextual/extension-methods.html ("Collective extensions like these are a shorthand for individual extensions where each method is defined separately...”)

**Comment by SethTisue** [comment]
oh, I get it now, Tom helped me on Gitter. `numeric` is itself an extension method and is added to the enclosing scope, but the `private` prevents it from escaping from there.

**Comment by griggt** [comment]
and in this particular case, since both `summon` and `numeric` are declared `inline`, the generated bytecode is simpler than other solutions (no additional method calls or field acceses):

```
  public <A> A cubed(A, scala.math.Numeric<A>);
    Code:
       0: aload_2
       1: aload_1
       2: aload_2
       3: aload_1
       4: aload_1
       5: invokeinterface #34,  3           // InterfaceMethod scala/math/Numeric.times:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
      10: invokeinterface #34,  3           // InterfaceMethod scala/math/Numeric.times:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
      15: areturn
```

**Comment by odersky** [comment]
So, I think we can consider this resolved?

**Comment by bmeesters** [comment]
@odersky is this really resolved? This feels like a decent workaround, but I have seen enough implicit classes with val definitions that I think the workaround is not idiomatic. Is there any reason not to support val in extensions (somewhere in the future)?

**Comment by bmeesters** [comment]
@odersky I know you are a busy man, but I do want to ask again whether there is any reason why `val` and `lazy val` could not be supported in extensions? They are currently possible in implicit classes and I would miss them when migrating to Scala 3.
