### ISSUE TITLE
Synthesise Mirror.Sum for Nested hierarchies

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty-feature-requests#161]
## Minimized code

```scala
sealed trait TreeValue

sealed trait SubLevel extends TreeValue

case class Leaf1(value: String) extends TreeValue
case class Leaf2(value: Int)    extends SubLevel
```

## Output

```scala
scala> import scala.compiletime._, scala.deriving._

scala> val m = summon[Mirror.Of[TreeValue]]
1 |val m = summon[Mirror.Of[TreeValue]]
  |                                    ^
  |no implicit argument of type deriving.Mirror.Of[TreeValue] was found for parameter x of method summon in object Predef
```

## Expectation

I expect a mirror to be summonable.

**Comment by julienrf** [comment]
I believe this is an important feature to support. Existing code that uses type-class derivation in Scala 2 does support this use case.

The summoned mirror should contain all the leaves of the hierarchy, not just the direct descendent leaves.

**Comment by YulawOne** [comment]
We as well, have multiple examples of such code in our codebase. Especially with https://github.com/ghostdogpr/caliban, or I would say anything that use Magnolia macro, which I think would make hard to migrate on Dotty if it's not supported, and maybe that is the reason why there is troubles with support for sealed trait hierarchies - https://github.com/propensive/magnolia/issues/246

**Comment by dwijnand** [comment]
Given my example above

> ```scala
> sealed trait TreeValue
> 
> sealed trait SubLevel extends TreeValue
> 
> case class Leaf1(value: String) extends TreeValue
> case class Leaf2(value: Int)    extends SubLevel
> ```

Does everyone agree that `Leaf1` values and `Leaf2` values should have an ordinal of 0 and 1, respectively?

Using my initial implementation I'm getting 1 and 0, and I'm pretty sure it's because SubLevel is getting ordinal=0 and Leaf 2 is resetting to 0.

**Comment by bishabosha** [comment]
If you haven't modified the `SyntheticMembers.ordinalBody` method I would assume the implementation looks as follows
```scala
def ordinal(value: MirroredMonoType): Int = value match
  case _: SubLevel => 0
  case _: Leaf1 => 1
```

as `Leaf2` is an instance of `SubLevel` it gets an ordinal of 0.
