### ISSUE TITLE
scalap - tasty files

### ISSUE THREAD

**Issue by xhudik** [lampepfl/dotty-feature-requests#186]
Hi, I'm wondering whether you are planning to include **some scala dis-assembler** into final Scala 3 version. 

`javap` is fine, but it writes out java language.  `scalac -Xprint:parser` is also fine but it works with source codes only. 
It would be great to have some class/tasty interpreter. I know there is `tasty-inspector` https://github.com/scala/scala3-tasty-inspector.g8 - but you still need to download the project link your stuff and build. _Having `tasty-inspector` as a command line tool - would be awesome_

**Comment by bishabosha** [comment]
Hello, currently you can do something like this `scalac -decompile path/to/Foo.tasty` which prints a source code representation of a TASTy file, and there is another flag `-print-tasty` for decomposition of TASTy in a human readable format, but still 1:1 with its binary representation. If you want to invoke the class manually you can run the main method of `dotty.tools.dotc.decompiler.Main`

**Comment by xhudik** [comment]
hmm, i tried:
```
scala3-compiler -decompile PatternMatching.tasty
bad option '-decompile' was ignored
^[[31m-- [E080] Syntax Error: PatternMatching.tasty:1:0 ------------------------------^[[0m
^[[31m1 |^[[0m\��^_����Scala (unknown)^@^U�Dr��^@^@��b�X�^@
  |^[[31m^^^^[[0m
  |Expected a toplevel definition
^[[31m-- Error: PatternMatching.tasty:1:23

scala3-compiler -print-tasty PatternMatching.tasty
^[[31m-- [E080] Syntax Error: PatternMatching.tasty:1:0 ------------------------------^[[0m
^[[31m1 |^[[0m\��^_����Scala (unknown)^@^U�Dr��^@^@��b�X�^@
  |^[[31m^^^^[[0m
  |Expected a toplevel definition
```
it seems none of them works :(

**Comment by bishabosha** [comment]
if you are using a coursier launcher then you want to use `scala3-decompiler`

**Comment by bishabosha** [comment]
actually, if you run `scala3-decompiler` from a different directory to where you compile the classfiles to then it works

**Comment by xhudik** [comment]
it seems even I try decompiler from different directory - it doesnt work es expected:
```
scala3-decompiler classes/EnumTypes\$.class
File extension is not `tasty` or `jar`: classes/EnumTypes$.class
File extension is not `tasty` or `jar`: classes/EnumTypes$.class
2 errors found
```

**Comment by bishabosha** [comment]
to decompile something you pass a tasty file, so i think the best chance is to use
```
scala3-decompiler -classpath classes classes/EnumTypes.tasty
```

**Comment by xhudik** [comment]
thanks @bishabosha  - this is it! It really works as expected. 
Maybe if the command line help is improved - more people would find this faster (without help of community) - but this is already another issue :). I'm closing this one - once more - thank you!
