### ISSUE TITLE
Make @tailrec a keyword

### ISSUE THREAD

**Issue by Lumintorious** [lampepfl/dotty-feature-requests#192]
`@tailrec` is a core part of writing recursion in Scala, is used consistently and is part of the main compiler, why not turn it into a keyword like for `@infix` and `@inline`

**Comment by smarter** [comment]
Because unlike these keywords, `@tailrec` does not change anything about the semantics of the code, it just does linting.

**Comment by Lumintorious** [comment]
Alright then, it was a nice dream.
