### ISSUE TITLE
Add Gradle-like closure:

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty-feature-requests#197]
# Introduction

In Scala we can do this:
```scala
class Test {
  var word: String = "I am mutable"
}

val test = Test {
  word = "Hello World"
}
```

Which is practical to represent relatively complexes instances in an aspect-oriented way like in [ScalaFX](http://scalafx.org/)

However, we actually can't do this:
```scala
val test = Test()
test {
  test = "Hello"
}
```

# The idea
My proposal is to implement the above example.

```scala
//Scope A
val test = Test()
test { //Scope A then Scope of test.*
  word = "Hello"
}
```

Translated by the compiler into:
```scala
val test = Test()
test.word = "Hello"
```

A deeper example:
```scala
class Style {
  var bold: Boolean = false
  var italic: Boolean = false
  var color: Color = White
}

object Style {
  @static val Raw: String = Style()
}

class Text {
  var plain: String = ""
  var style: Style = Style.Raw
}

//Scope A
val test = Test
test { //Scope A then Scope of test.*
  plain = "Hello"
  style = Style {
    bold = true
    color = Red
  }
}
```

# Avoiding scope clash
To avoid ambiguity, we should be able to use external scopes' attributes then our nested's one:
```scala
//Scope A
var world: Int = 0
val test = Test()
test {
  word = "Hello" //Error: type mismatch String → Int
  this.word = "Hello" 
}
```

If inside a class:
```scala
class Foo {
    var word: Boolean = false
    def test(): Unit = {
        var world: Int = 0
        val test = Test()
        test {
          word = "Hello" //Error: type mismatch String → Int
          this.word = "Hello" //Error type mismatch String → Boolean
          Test.this.word = "Hello"
        }
    }
}
```

**Comment by LPTK** [comment]
Sorry, but this is never going to be seriously considered.

First, because it clashes with `apply` functions also being callable as `obj { ... }`.

Second, because Scala emphasizes immutability, and is not going to introduce a new weird feature just to let users mutate variables more easily.

Third, because the idiomatic way of doing this kind of things in Scala is:

```scala
case class Test(word: String = "default value", ...)

val test = Test(...)

test.copy(word = "new value")
```

Fourth, because if you really want to mutate stuff, you can always do:

```scala
locally:
  import test._
  word = "new value"
```

**Comment by Iltotore** [comment]
I wasn't aware of that method:
```scala
locally:
  import test._
  word = "new value"
```

Thank you !
