### ISSUE TITLE
Discuss of Type Projection.

### ISSUE THREAD

**Issue by djx271** [lampepfl/dotty-feature-requests#204]
Delete for never discuss

**Comment by som-snytt** [comment]
Still not translated: https://github.com/lampepfl/dotty-feature-requests/issues/14

**Comment by tribbloid** [comment]
Many of those links are also broken. @djx271 what's going on here? 搞什么飞机？

**Comment by djx271** [comment]
Two years ago, I was too anxious and create the issue when the phased work was not completed. I'm really sorry. 
I'll describe it again later and look for a translator.

**Comment by djx314** [comment]
Type Projection 对应了一般程序中的对象方法调用，它可以实现一些加减乘除运算。
```scala
trait Number1 {
  type method1[number2 <: Number2] <: Number3
}
class Number1S[Tail <: Number1] extends Number1 {
  override type method1[number2 <: Number2] = number2#method2[Tail]
}
class Number1T[Tail <: Number1] extends Number1 {
  override type method1[number2 <: Number2] = Number3S[Tail#method1[number2]]
}
class Number1U[Tail <: Number1] extends Number1 {
  override type method1[number2 <: Number2] = Number3S[number2#method2[Tail]]
}

trait Number2 {
  type method2[number1 <: Number1] <: Number3
}
class Number2S[tail <: Number2] extends Number2 {
  override type method2[number1 <: Number1] = number1#method1[tail]
}
class Number2T extends Number2 {
  override type method2[number1 <: Number1] = Number3T
}

trait Number3
class Number3S[Tail <: Number3] extends Number3
class Number3T                  extends Number3

class number1ZeroU extends Number1U[number1ZeroU]

class Tag[T]
object Tag {
  def apply[T]: Tag[T] = new Tag[T]
}
def i[T](tag1: Tag[T], tag2: Tag[T]): List[Tag[T]] = List(tag1, tag2)

type Num1 = Number1T[Number1T[Number1T[number1ZeroU]]]
type Num2 = Number2S[Number2S[Number2S[Number2S[Number2T]]]]
type Num3 = Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3T]]]]]]]

i(Tag[Num2#method2[Num1]], Tag[Num3])

class Num1     extends Number1T[Number1T[Number1T[Num1Zero]]]
class Num1Zero extends Number1S[Num1]
type Num2 = Number2S[Number2S[Number2S[Number2S[Number2T]]]]
type Num3 =
Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3S[Number3T]]]]]]]]]]]]

i(Tag[Num2#method2[Num1]], Tag[Num3])
i(Tag[Num1Zero#method1[Num2]], Tag[Num3])
```

详细的代码可以见 [ghdmzsk/v1/b01](https://github.com/ghdmzsk/v1/tree/master/b/b01) ，在 [ghdmzsk/v1/a01](https://github.com/ghdmzsk/v1/tree/master/a/a01) 中给出了更详细的运行时对应版本。

根据 [ghdmzsk/v1/a03](https://github.com/ghdmzsk/v1/tree/master/a/a03) 的提示，这里保留了与结果值偏差正 1 和负 1 的结果。在整数加减法（a03）中，作为自然数的进一步演化，准确结果将被隐藏。

运用 Type Projection 可以以面向对象的形式对自然数进行四则运算，运用 Match Types 则可以对运算过程进行判断语句操作，双方都可以实现循环。个人认为可以从这方面考虑 Type Projection 的理论依归。

**Comment by djx314** [comment]
If you just want to read the code. Click

[ghdmzsk/v1/b01](https://github.com/ghdmzsk/v1/tree/master/b/b01)

[ghdmzsk/v1/a01](https://github.com/ghdmzsk/v1/tree/master/b/a01)

is OK.

**Comment by djx271** [comment]
Closeing for finding that Match Types can replace all use of Type Projection.

**Comment by djx271** [comment]
Closeing for finding that Match Types can replace all use of Type Projection.
