### ISSUE TITLE
Why traits cannot have context bound since traits not support implicit parameters?

### ISSUE THREAD

**Issue by ireina7** [lampepfl/dotty-feature-requests#219]
I suggest to have trait context bound for the following reasons:

I really love dotty's typeclass functions. However, I feel a little annoying to redefine many unnecessary methods. For example, I want to define `Functor`:
```scala
trait Functor[F[_]]:
  extension [A](x: F[A])
    def map[B](f: A => B): F[B]
```
However, in defining `Monad`:
```scala
trait Monad[F[_]] extends Functor[F]:
  def pure[A](x: A): F[A]
  extension [A](x: F[A])
    def flatMap[B](f: A => F[B]): F[B]
    //def map[B](f: A => B) = x.flatMap(f.andThen(pure))
end Monad
```
I totally understand that `map` can be defined by `flatMap` in defining `Monad`. However, in real world, there're many typeclasses cannot be redefined as easy as this example. It's a little annoying that I have to repeat methods like `map` again and again.

If I can use trait context bounds, then:
```scala
trait Monad[F[_]: Functor]:
  def pure[A](x: A): F[A]
  extension [A](x: F[A])
    def flatMap[B](f: A => F[B]): F[B]
```
which can be unfolded as:
```scala
trait Monad[F[_]](using Functor[F]):
  def pure[A](x: A): F[A]
  extension [A](x: F[A])
    def flatMap[B](f: A => F[B]): F[B]
```
Finally no `map` function is needed in defining `Monad`.

**Comment by smarter** [comment]
What do you mean exactly? The syntax you describe already works in Scala 3.0.0.

**Comment by ireina7** [comment]
Thank you! Can you please give a link on this function? I cannot compile this right now.

**Comment by smarter** [comment]
Here's an example showing that the code you wrote does compile: https://scastie.scala-lang.org/g7YanEHSR8CySB2TrkySAQ

**Comment by ireina7** [comment]
Thanks a lot! I understand now, there's something wrong with my compiler. Sorry for requesting repeated feature. However, I'd like to see some updates on the documentation, Scala3's doc still use `extends` to demonstrate typeclasses right now.

**Comment by smarter** [comment]
There are advantages and disadvantages to both approaches, for the documentation we're just showing one simple example but people are free to experiment with different approaches, for example see the discussion in https://contributors.scala-lang.org/t/encoding-type-class-hierarchies/4626

**Comment by ireina7** [comment]
I see, thank you very much!
