### ISSUE TITLE
In the binary distribution, add scripts for Windows systems

### ISSUE THREAD

**Issue by concastinator** [lampepfl/dotty-feature-requests#226]
Currently, if one wants to bypass `sbt` and `coursier` anf go "full ninja", one may download the Scala binary distribution from GitHub. Alas, the `scala` and `scalac` scripts included therein are `bash` scripts, which are useless in Windows. (Unless one accepts using the Linux Subsytem for Windows, which is a very twisted and unnatural way of using software.) The Kotlin binary distribution includes, for every command, both a `bash` script and a `.bat` script, making that software easily usable everywhere. Could the Scala team do the same and include `.bat` equivalents of these `bash` scripts? Thank you.

**Comment by liufengyun** [comment]
See https://github.com/lampepfl/dotty/pull/13006

**Comment by dwijnand** [comment]
Merged

**Comment by concastinator** [comment]
@dwijnand: Shall we see the change in the next release (i.e. 3.0.1-RC3 or even 3.0.1 proper)?

**Comment by dwijnand** [comment]
So the PR was merged into master.  3.0.1 is being released (https://github.com/lampepfl/dotty/issues/13025) from the https://github.com/lampepfl/dotty/tree/release-3.0.1 branch, so it won't be in that.  But I think 3.0.2-RC1 will be release off of master, so it very well might be in that one.  If not then in 3.1.0, which should follow 3.1.0 in terms of releases, though with some time delay.
