### ISSUE TITLE
Announce releases on SDKMAN!

### ISSUE THREAD

**Issue by helpermethod** [lampepfl/dotty-feature-requests#233]
Hi!

It would be amazing if new releases could be announced automatically via SDKMAN!'s [Vendor API](https://sdkman.io/vendors).

Currently new releases are added manually by the community, which often results in missing release versions, or versions which show up long after release.

Wdyt? If you need any help, let me know!

**Comment by DavidGregory084** [comment]
This seems to have been resolved in lampepfl/dotty#13885

**Comment by helpermethod** [comment]
Jup, thanks alot!

**Comment by ckipp01** [comment]
> This seems to have been resolved in [lampepfl/dotty#13885](https://github.com/lampepfl/dotty/pull/13885)

Going to go ahead and close this then.
