### ISSUE TITLE
Unify string interpolation and XML interpolation

### ISSUE THREAD

**Issue by sasha2048** [lampepfl/dotty-feature-requests#240]
Currently:
  * To put a value into the string, user needs to prepend it with `$` (or both prepend with `$` and surround with `{…}`): `s"Item count is $itemCount"` (or `s"Item count is ${itemCount}"`).
  * To put a value into XML, user needs to surround it with `{…}`: `<span>Item count is {itemCount}</span>`.

The following, of course, doesn't work: `s"Item count is {itemCount}"`, `<span>Item count is $itemCount</span>`.

The simplest solution would be to create add one more string interpolator — say, `b"Item count is {itemCount}"`. It will have the following benefits:
 1. Similarly looking syntax with XML interpolator (e.g. handy when you're moving stuff between strings and XML).
 2. Single syntax for simple expressions and complex expressions: `s"$value and then ${value+1}"` → `b"{value} and then {value + 1}"` (or, if you always use `${…}`, even for simple expressions, then `{…}` is just cleaner).

**Comment by SethTisue** [comment]
> The simplest solution would be to create add one more string interpolator

the use of `$` to introduce interpolated items is built-in at the language level, as per https://docs.scala-lang.org/overviews/core/string-interpolation.html , so I believe you are asking for a design change to how string interpolation in general works, not merely asking for "one more string interpolator"

**Comment by SethTisue** [comment]
also, Scala's XML syntax has been considered legacy for a long time now and is well into the process of being phased out entirely, so I expect you would need a stronger design justification for this than just "unify with XML"

(string interpolation was added to Scala some years after XML support was added; if string interpolation had existed first, language-level XML support would probably never have been added at all)

**Comment by sasha2048** [comment]
@SethTisue, on the one hand, I like `{name}` style more than `$name` and/or `${name}`. On the other hand, I like the idea to phase out XML support, because I feel its syntax (in Scala) to be not-fully-consistent per se (I was even thinking about making a separate feature request for that).

Probably I should close this request.

P.S. Do you know — is there another feature allowing to generate XML quickly (something quicker than just calling scala.xml.Elem constructors directly, which can be used instead of that going-to-be-phased-out language-level XML support)?

**Comment by smarter** [comment]
There's https://github.com/lampepfl/xml-interpolator/ but it's in need of a maintainer.
