### ISSUE TITLE
Converting a Class object to Type[T] and use T in Macro programming

### ISSUE THREAD

**Issue by HalfLegend** [lampepfl/dotty-feature-requests#275]
This is my question: 
https://stackoverflow.com/questions/70575546/scala-3-macro-generic-type-from-class

Now scala 3 provides the behavior to convert a Class object to Type[T].
But what's the next? 
What could I do with the Type[T] object?
I could not use the T under Type[T].

The current implementation to convert from Class to Type[T] is of no use in Macro programming....

**Comment by LPTK** [comment]
I've answered your question on the website. I think you can close this issue now.

**Comment by ckipp01** [comment]
> I've answered your question on the website. I think you can close this issue now.

Looks like this is referring to https://stackoverflow.com/questions/70575546/scala-3-macro-generic-type-from-class. I'll go ahead and close, but please do comment back if this isn't the case.
