### ISSUE TITLE
Dottydoc needs to be responsive

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty-feature-requests#28]
The doc tool currently pretty much only supports desktop, since there are no rules for mobile devices.

Since the documentation is using bootstrap 4, we should adapt to using its preferred method of handling reactive sizing.

**Comment by TheElectronWill** [comment]
I'm on it :smiley:  Will submit a PR soon to make Dottydoc fully responsive.

**Comment by TheElectronWill** [comment]
See https://github.com/lampepfl/dotty/pull/7153
