### ISSUE TITLE
Extend kind-projector support

### ISSUE THREAD

**Issue by Daenyth** [lampepfl/dotty-feature-requests#285]
For projects that cross-compile scala 2 and scala 3, certain uses of kind-projector style type projection have become extremely painful, for example in:

- [rediculous](https://github.com/davenverse/rediculous/blob/main/core/src/main/scala/io/chrisdavenport/rediculous/Redis.scala#L71)
- [droste](https://github.com/higherkindness/droste/pull/206/files#diff-4670f534f1432a6921c08e3aaf5907714bd8a1404bab88dd87f6a5685aa63220L164)

Previous description on lampepfl/dotty#7775:
@djspiewak in https://github.com/lampepfl/dotty/issues/7775#issuecomment-633355853

**Comment by ckipp01** [comment]
There seems to be quite a bit more info in https://github.com/lampepfl/dotty/discussions/17673, so I'll close this one if favor of that. If something is missing from here, please do add it to the other request.
