### ISSUE TITLE
add support for -Wunused

### ISSUE THREAD

**Issue by pelamfi** [lampepfl/dotty-feature-requests#287]
build.sbt with

```
scalaVersion := "3.0.0"
scalacOptions ++= Seq("-Wunused")
```

Produces:
```
[error] bad option '-Wunused' was ignored
```

**Comment by som-snytt** [comment]
Taking a look now. I'm willing to entertain any preconceived notions. I haven't looked at current Scalafix yet.

Sample urgency:
```
-- Warning: t9440-lrytz.scala:4:8 ---------------------------------------------------------------------------------------------------------------
4 |@nowarn("cat=unused-nowarn")
  |        ^^^^^^^^^^^^^^^^^^^
  |        Invalid message filter
  |        unknown category: unused-nowarn
1 warning found
```
We may not be 100% cat-compatible.

**Comment by bbarker** [comment]
Hi @som-snytt , just curious if you had any further finds.

More generally, maybe someone could briefly describe the compiler phases that would be best to take a look at in implementing this feature and any other high-level suggestions. Thanks!

**Comment by som-snytt** [comment]
unused imports is at https://github.com/lampepfl/dotty/pull/14524

**Comment by hartmut27** [comment]
see [lampepfl/dotty/pull/16157](https://github.com/lampepfl/dotty/pull/16157)

**Comment by kubukoz** [comment]
I think we can close it indeed. There are some edges to clean up but we have issues tracking that.
