### ISSUE TITLE
Publish compiler API docs

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty-feature-requests#293]
In Scala 2 there are the library API docs and also the [compiler api docs](https://www.scala-lang.org/api/2.13.8/scala-compiler/index.html). This is useful for browsing the cos for `interactive` for example. As far as I can tell for Scala 3 not everything [seems to be published](https://scala-lang.org/api/3.x/). It'd be great to also have the compiler APIs published like in Scala 2.

**Comment by SethTisue** [comment]
are they available on https://javadoc.io ?

**Comment by ckipp01** [comment]
Ahhhh they are! https://javadoc.io/doc/org.scala-lang/scala3-compiler_3/3.1.1-RC2/index.html
