### ISSUE TITLE
Consider including kotlin-style `let` and `also` in predef

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty-feature-requests#322]
Those are very useful and now can finally be implemented without runtime overhead.

```scala
Builder
  .enableStuff()
  .let { b =>
    if (enableOtherStuff) b.enableOtherStuff() else b
  }
  .enableMoarStuff()
  .build()
```

```scala
new Thread().also { t =>
  t.setDaemon(false)
}
```

**Comment by LPTK** [comment]
They're already available as `pipe` and `tap` from [scala.util.ChainingOps](https://www.scala-lang.org/api/2.13.6/scala/util/ChainingOps.html).

**Comment by SethTisue** [comment]
implementation and design discussions: https://github.com/scala/scala/pull/7007
