### ISSUE TITLE
Use colon as alternative of "extends"

### ISSUE THREAD

**Issue by diesalbla** [lampepfl/dotty-feature-requests#64]
In the class or object declaration, allow using a single colon `:` as an alternative of the `extends` keyword to declare the super-class or super-trait. 

As an example, consider the following traits and declarations: 
```Scala
trait A { 
  def x: Int 
}

object B extends A {
  val x = 13
 }
class C(y: Int) extends A { 
  val x = y + 1
}
class D(z: Int) extends C(z+1)
```

The proposed change would allow writing the object and classes as follows: 
```Scala
object B: A { 
  val x = 13
} 
class C(y: Int): A {
  val x = y + 1
}
class D(z: Int): C(z+1)
```

A possible benefit of this change is that it makes more similar the definition of a named anonymous instance, or instance factory, and that of an object or class. Following on the previous example, consider the following definitions of named/anonymous instances: 

```Scala
trait A

object C extends A { val x = 13 }
val b: A = new A { val x = 13 }

class C(y: Int) extends A { val x = y + 1}
def c(y: Int): A = new A { val x = y + 1}
```

With this change, those would become: 

```Scala
trait A

object C: A { val x = 13 }
val b: A = new A { val x = 13 }

class C(y: Int): A { val x = y + 1 }
def c(y: Int): A = new A { val x = y + 1 }
```

##### Effort estimation

Optimistically: to implement this change one would just have to go for the syntax rule in which the `extends` token keyword is used, and allow using also the colon `:` token instead. However, there is the risk of introducing some ambiguities in the Scala grammar.

##### Precedent
This syntax is already used in [Kotlin](https://kotlinlang.org/docs/reference/classes.html#inheritance).

**Comment by neko-kai** [comment]
@diesalbla Note that there's already `<:` as an alternative for `extends`. You may write `trait A <: B` and this means the same as `trait A extends B` - this is legal (but deprecated, same as view bounds) Scala 2 syntax.

**Comment by som-snytt** [comment]
The other consideration is
```
scala> class C:
     |   def c = 42
     |
// defined class C

scala> class D: C    // ??!
```

This would correspond to "optional extends" in Scala 2:
```
scala 2.13.2> class C extends {
            |   def c = 42
            | }
class C

scala 2.13.2> class D extends C
class D
```
but doti demurs
```
scala> class D extends {
1 |class D extends {
  |                ^
  |                `extends` must be followed by at least one parent
```
