### ISSUE TITLE
syntactic sugar for delegation

### ISSUE THREAD

**Issue by robstoll** [lampepfl/dotty-feature-requests#85]
One feature I miss in Scala is a way to delegate without a lot of boilerplate (maybe there is already a way I am not aware of?). 
See Kotlin's implementation by delegation feature:
https://kotlinlang.org/docs/reference/delegation.html#implementation-by-delegation

In short:
```scala
trait A  { def foo(): String }
class B extends A{
  override def foo(): String = ???
}
class C(b: B) extends A by B
```

I would imagine that scala goes even a step further and supports this feature not only on a trait level but also per function. This way one can delegate a function to another function without the need to repeat the arguments. For instance:
```scala
def foo(i: Int) = ???
def bar(i: Int) by foo
```
It gets trickier as soon as a function has multiple parameter lists. Basically it should just stupidly fill up the missing parameter lists. I would expect something like the following:
```scala
  def foo(i: Int)(s: String): String

  def test1(i: Int)(s: String): String by foo          // translates to: foo(i)(s)
  def test2(s: String): String by foo(2)               // translates to: foo(2)(s)
  def test3(i: int)(s: String) : String by foo(i + 1)  // translates to: foo(i + 1)(s)

  def err1(l: Long)(s: String): String by foo          // translates to: foo(l)(s) => error Int as arg expected but Long given
  def err2(s: String)(i: Int): String by foo(i + 1)    // translates to: foo(i + 1)(i) => error String as arg expected but Int given
  def err3(i: Int): String by foo                      // translates to: foo(i) => error, String as return value expected but String -> String given
  
  // here we see that it stupidly translates, could come in handy though
  def err4(i: Int)(s: String)(l: Long)                 // translates to: foo(i)(s)(l) => error, String.apply expects Int, Long given
```

As it is only syntactic sugar it can deal with all kind of features not talked about here such as default arguments, implicit arguments etc.

IMO the keyword does not have to be `by`

**Comment by SethTisue** [comment]
https://dotty.epfl.ch/docs/reference/other-new-features/export.html

**Comment by robstoll** [comment]
Looking forward to dotty 🙂
Any chance this gets into scala 2.14?

**Comment by SethTisue** [comment]
> Any chance this gets into scala 2.14?

I don't believe so, no.

**Comment by hepin1989** [comment]
https://projectlombok.org/features/experimental/Delegate can do a similar thing
